name: talisman Validation
on:
  pull_request:
    branches: [main]

jobs:
  talisman_Scan:
    runs-on: kubecli
    container:
      image: "dshivakumar/talisman:root"
    permissions:
      pull-requests: write 
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Mark repo as safe for Git
        run: |
          git config --global --add safe.directory /__w/DevSecOps/DevSecOps
      - name: Debug Git Info
        run: |
          git rev-parse --is-inside-work-tree
          git status
      - name: Run Talisman Scan
        id: talisman
        run: |
          set +e
          git add . # Stage all files to ensure scan detects changes
          talisman --scan
          talisman --scan > talisman_output.txt 2>&1
          cat talisman_output.txt
          echo "exit_code=$?" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT 
          cat talisman_report/talisman_reports/data/report.json
        continue-on-error: true
      - name: Update PR Comments
        if: steps.talisman.outputs.exit_code != 0
        run: | 
          echo "Secrets Detected By talisman: "
          cat talisman_output.txt 
          COMMENT="** talisman DETECTED SECRETS IN PR. **\n\n $(cat talisman_output.txt) \n"
          gh pr comment "$PR_URL" --body "$COMMENT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
      - name: Close PR if secrets found
        if: steps.talisman.outputs.exit_code != '0'
        env:
          GITHUB_TOKEN: ${{ secrets.PR_SEC_PAT }}  # Use a PAT with repo permissions
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          echo "Closing PR #$PR_NUMBER due to detected secrets"
          gh pr close "$PR_NUMBER" --repo "$REPO" --comment "Closing this PR because Talisman detected secrets. Please remove the secrets and reopen."


