name: talisman Validation
on:
  pull_request:
    branches: [main]

jobs:
  talisman_Scan:
    runs-on: kubecli
    container:
      image: "dshivakumar/talisman:root"
    permissions:
      pull-requests: write 
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4.2.2
      - name: Run Talisman Scan
        id: talisman
        run: |
          set +e
          talisman --scan > talisman_output.txt 2>&1
          echo "exit_code=$?" >> $GITHUB_OUTPUT
        continue-on-error: true
      - name: Update PR Comments
        if: steps.talisman.outputs.exit_code != 0
        run: | 
          echo "Secrets Detected By talisman: "
          cat talisman_output.txt 
          COMMENT="** talisman DETECTED SECRETS IN PR. **\n\n $(cat talisman_output.txt) \n"
          gh pr comment "$PR_URL" --body "$COMMENT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

